name: $(Rev:r)
trigger:
  branches:
    include:
    - master
pr: 
  branches: 
    include:
    - master

jobs:

- job: Phase_1
  displayName: 'Hosted macOS Job'
  condition: succeeded()
  workspace:
    clean: all
  pool:
    name: Hosted macOS

  steps:
    
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.0.100'
    inputs:
      packageType: 'sdk'
      version: '3.0.100'

  - template: templates/install-cake.yml 

  - script: |
       sudo chmod +x xamarin_sdk_version.sh
       ./xamarin_sdk_version.sh
    displayName: 'Pin Xcode / Xamarin / Mono versions'

  - task: CmdLine@2
    displayName: 'Invoke HealthCheck'
    condition: succeededOrFailed()
    inputs:
      script: 'dotnet-cake --target=HealthCheck'

  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Report Warnings'
    condition: succeededOrFailed() 
    inputs:
      checkWarnings: true
      warningThreshold: '0'
      baseRepoId: 'db8ec2f5-e6a9-4855-a6a2-1969621908e4'
      baseBranchRef: refs/heads/master
      warningTaskFilters: '/Invoke HealthCheck'
      includePartiallySucceeded: false