variables:
- group: Mobile Settings

name: $(Rev:r)
trigger: none

jobs:

- job: Phase_1
  displayName: 'Hosted macOS Job'
  condition: succeeded()
  workspace:
    clean: all
  pool:
    name: Hosted macOS

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.0.100'
    inputs:
      packageType: 'sdk'
      version: '3.0.100'

  - template: templates/install-cake.yml 

  - task: CmdLine@2
    displayName: 'Invoke HealthCheck'
    condition: succeededOrFailed()
    inputs:
      script: 'dotnet-cake --target=HealthCheck --vsts_username=$(VstsUsername) --vsts_token=$(VstsAccessToken)'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()

  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Report Warnings'
    inputs:
      checkWarnings: true
      warningTaskFilters: '/Invoke HealthCheck'
      baseDefinitionId: 11
      baseRepoId: 'db8ec2f5-e6a9-4855-a6a2-1969621908e4'
      baseBranchRef: refs/heads/master
    condition: succeededOrFailed()